name: laravel-chat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        cat <<EOF > .env
        APP_NAME=${{ secrets.APP_NAME }}
        APP_ENV=${{ secrets.APP_ENV }}
        APP_KEY=${{ secrets.APP_KEY }}
        APP_DEBUG=${{ secrets.APP_DEBUG }}
        APP_URL=${{ secrets.APP_URL }}

        LOG_CHANNEL=${{ secrets.LOG_CHANNEL }}

        DB_CONNECTION=${{ secrets.DB_CONNECTION }}
        DB_HOST=${{ secrets.DB_HOST }}
        DB_PORT=${{ secrets.DB_PORT }}
        DB_DATABASE=${{ secrets.DB_DATABASE }}
        DB_USERNAME=${{ secrets.DB_USERNAME }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}

        BROADCAST_DRIVER=${{ secrets.BROADCAST_DRIVER }}
        CACHE_DRIVER=${{ secrets.CACHE_DRIVER }}
        QUEUE_CONNECTION=${{ secrets.QUEUE_CONNECTION }}
        SESSION_DRIVER=${{ secrets.SESSION_DRIVER }}
        SESSION_LIFETIME=${{ secrets.SESSION_LIFETIME }}

        REDIS_HOST=${{ secrets.REDIS_HOST }}
        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
        REDIS_PORT=${{ secrets.REDIS_PORT }}

        MAIL_MAILER=${{ secrets.MAIL_MAILER }}
        MAIL_HOST=${{ secrets.MAIL_HOST }}
        MAIL_PORT=${{ secrets.MAIL_PORT }}
        MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
        MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}
        MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}
        MAIL_FROM_NAME="${{ secrets.MAIL_FROM_NAME }}"

        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
        AWS_BUCKET=${{ secrets.AWS_BUCKET }}

        PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}
        PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}
        PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}
        PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}
        EOF

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image locally
      run: |
        docker build -t laravel-chat .

    - name: Stop and Remove existing container
      run: |
        docker stop laravel-chat || true
        docker rm laravel-chat || true

    - name: Deploy Docker container
      run: |
        docker run -d \
          -p 9000:80 \
          --name laravel-chat \
          --env-file .env \
          --restart unless-stopped \
          laravel-chat

    - name: Check running container
      run: |
        docker ps -q -f name=laravel-chat | grep -q . && echo "Container is running" || echo "Container is not running"

    - name: Clean up
      run: |
        rm -rf ${{ github.workspace }}/*
